# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Dec 14 02:51:35 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(235, 489)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setText("a")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_generator_a = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_generator_a.setObjectName("lineEdit_generator_a")
        self.gridLayout_2.addWidget(self.lineEdit_generator_a, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setText("b")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_generator_b = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_generator_b.setObjectName("lineEdit_generator_b")
        self.gridLayout_2.addWidget(self.lineEdit_generator_b, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setText("λ")
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit_servicemachine_lambda = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_servicemachine_lambda.setObjectName("lineEdit_servicemachine_lambda")
        self.gridLayout_3.addWidget(self.lineEdit_servicemachine_lambda, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.label_deltat = QtWidgets.QLabel(self.groupBox_3)
        self.label_deltat.setObjectName("label_deltat")
        self.gridLayout.addWidget(self.label_deltat, 3, 0, 1, 1)
        self.comboBox_method = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_method.setObjectName("comboBox_method")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.gridLayout.addWidget(self.comboBox_method, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEdit_request_count = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_request_count.setObjectName("lineEdit_request_count")
        self.gridLayout.addWidget(self.lineEdit_request_count, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.lineEdit_reenter_probability = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_reenter_probability.setObjectName("lineEdit_reenter_probability")
        self.gridLayout.addWidget(self.lineEdit_reenter_probability, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.lineEdit_deltat = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_deltat.setObjectName("lineEdit_deltat")
        self.gridLayout.addWidget(self.lineEdit_deltat, 3, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_res_reentered_count = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_res_reentered_count.setReadOnly(True)
        self.lineEdit_res_reentered_count.setObjectName("lineEdit_res_reentered_count")
        self.gridLayout_4.addWidget(self.lineEdit_res_reentered_count, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.lineEdit_res_max_queue_size = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_res_max_queue_size.setReadOnly(True)
        self.lineEdit_res_max_queue_size.setObjectName("lineEdit_res_max_queue_size")
        self.gridLayout_4.addWidget(self.lineEdit_res_max_queue_size, 2, 1, 1, 1)
        self.lineEdit_res_request_count = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_res_request_count.setReadOnly(True)
        self.lineEdit_res_request_count.setObjectName("lineEdit_res_request_count")
        self.gridLayout_4.addWidget(self.lineEdit_res_request_count, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_res_time = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_res_time.setReadOnly(True)
        self.lineEdit_res_time.setObjectName("lineEdit_res_time")
        self.gridLayout_4.addWidget(self.lineEdit_res_time, 3, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)

        self.retranslateUi(Form)
        self.comboBox_method.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", ":3"))
        self.groupBox.setTitle(_translate("Form", "Параметры генератора"))
        self.lineEdit_generator_a.setText(_translate("Form", "1"))
        self.lineEdit_generator_b.setText(_translate("Form", "10"))
        self.groupBox_2.setTitle(_translate("Form", "Параметры ОА"))
        self.lineEdit_servicemachine_lambda.setText(_translate("Form", "1"))
        self.groupBox_3.setTitle(_translate("Form", "Свойства системы"))
        self.label_deltat.setText(_translate("Form", "Δt"))
        self.comboBox_method.setItemText(0, _translate("Form", "Событийный"))
        self.comboBox_method.setItemText(1, _translate("Form", "Δt"))
        self.label_5.setText(_translate("Form", "Количество заявок"))
        self.lineEdit_request_count.setText(_translate("Form", "1000"))
        self.label_7.setText(_translate("Form", "Метод моделирования"))
        self.lineEdit_reenter_probability.setText(_translate("Form", "0"))
        self.label_6.setText(_translate("Form", "Вероятность повторной\n"
"обработки заявки"))
        self.lineEdit_deltat.setText(_translate("Form", "0.1"))
        self.groupBox_4.setTitle(_translate("Form", "Результаты"))
        self.label_9.setText(_translate("Form", "Количество повторно\n"
"обработанных заявок"))
        self.label_10.setText(_translate("Form", "Максимальная длина\n"
"очереди"))
        self.label_8.setText(_translate("Form", "Количество обработанных\n"
"заявок"))
        self.label_4.setText(_translate("Form", "Время работы"))
        self.pushButton.setText(_translate("Form", "Моделировать"))

