from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(516, 313)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelStatesCount = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStatesCount.sizePolicy().hasHeightForWidth())
        self.labelStatesCount.setSizePolicy(sizePolicy)
        self.labelStatesCount.setObjectName("labelStatesCount")
        self.gridLayout_2.addWidget(self.labelStatesCount, 0, 0, 1, 1)
        self.spinBoxStatesCount = QtWidgets.QSpinBox(self.groupBox)
        self.spinBoxStatesCount.setObjectName("spinBoxStatesCount")
        self.gridLayout_2.addWidget(self.spinBoxStatesCount, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.tableWidgetMatrix = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidgetMatrix.setObjectName("tableWidgetMatrix")
        self.tableWidgetMatrix.setColumnCount(0)
        self.tableWidgetMatrix.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidgetMatrix, 1, 0, 1, 3)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonSolve = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonSolve.setObjectName("pushButtonSolve")
        self.verticalLayout.addWidget(self.pushButtonSolve)
        self.listWidgetSolution = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidgetSolution.setMaximumSize(QtCore.QSize(100, 16777215))
        self.listWidgetSolution.setObjectName("listWidgetSolution")
        self.verticalLayout.addWidget(self.listWidgetSolution)
        self.gridLayout.addWidget(self.groupBox_2, 1, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Состояния"))
        self.groupBox.setTitle(_translate("Form", "Входные данные"))
        self.labelStatesCount.setText(_translate("Form", "Матрица(Кол-тво состояний):"))
        self.groupBox_2.setTitle(_translate("Form", "Вывод"))
        self.pushButtonSolve.setText(_translate("Form", "Вычислить"))

